/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wijesekara.stores.pos;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Samintha
 */
public class AddUpdateSupplierUI extends javax.swing.JFrame {

    /**
     * Creates new form AddUpdateSupplierUI
     */
    public AddUpdateSupplierUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        upd_supname_txt = new javax.swing.JTextField();
        upd_supcontact_txt = new javax.swing.JTextField();
        upd_supaddr_txt = new javax.swing.JTextField();
        upd_supemail_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        upd_supupdate_btn = new javax.swing.JButton();
        upd_supdelete_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ins_supname_txt = new javax.swing.JTextField();
        ins_supcontact_txt = new javax.swing.JTextField();
        ins_supaddr_txt = new javax.swing.JTextField();
        ins_supemail_txt = new javax.swing.JTextField();
        ins_supadd_btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        upd_supid_txt = new javax.swing.JTextField();
        upd_supgo_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add or Update Supplier");
        setResizable(false);

        jLabel1.setText("Update/Delete Supplier");

        jLabel2.setText("Name :");

        jLabel3.setText("Contact :");

        jLabel4.setText("Address :");

        jLabel5.setText("Email :");

        jLabel6.setText("Insert a New Supplier");

        upd_supupdate_btn.setText("Update Supplier");
        upd_supupdate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_supupdate_btnActionPerformed(evt);
            }
        });

        upd_supdelete_btn.setText("Delete Supplier");
        upd_supdelete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_supdelete_btnActionPerformed(evt);
            }
        });

        jLabel7.setText("Name :");

        jLabel8.setText("Contact :");

        jLabel9.setText("Address :");

        jLabel10.setText("Email :");

        ins_supadd_btn.setText("Add Supplier");
        ins_supadd_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_supadd_btnActionPerformed(evt);
            }
        });

        jLabel11.setText("Supplier ID :");

        upd_supgo_btn.setText("GO");
        upd_supgo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_supgo_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel11))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(upd_supname_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                            .addComponent(upd_supcontact_txt)
                                            .addComponent(upd_supaddr_txt)
                                            .addComponent(upd_supemail_txt)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(upd_supid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(upd_supgo_btn))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ins_supname_txt)
                                            .addComponent(ins_supcontact_txt)
                                            .addComponent(ins_supaddr_txt)
                                            .addComponent(ins_supemail_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 117, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(upd_supdelete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(upd_supupdate_btn))
                            .addComponent(ins_supadd_btn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(upd_supid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upd_supgo_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(upd_supname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(upd_supcontact_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(upd_supaddr_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upd_supemail_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upd_supupdate_btn)
                    .addComponent(upd_supdelete_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ins_supname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ins_supcontact_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ins_supaddr_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ins_supemail_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ins_supadd_btn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upd_supgo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_supgo_btnActionPerformed
        // go button
        Supplier sup = new Supplier();
        sup.connectDB();
        List list = sup.getSupplierDetails(upd_supid_txt.getText());
        if (!list.isEmpty()) {
            upd_supname_txt.setText((String) list.get(1));
            upd_supcontact_txt.setText((String) list.get(2));
            upd_supaddr_txt.setText((String) list.get(3));
            upd_supemail_txt.setText((String) list.get(4));
        } else {
            JOptionPane.showMessageDialog(null, "Supplier ID not valid!");
        }
        sup.closeConnection();
    }//GEN-LAST:event_upd_supgo_btnActionPerformed

    private void ins_supadd_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_supadd_btnActionPerformed
        // insert supplier
        Supplier sup = new Supplier();
        sup.connectDB();
        if (ins_supname_txt.getText().trim().equals("") || ins_supcontact_txt.getText().trim().equals("") || ins_supaddr_txt.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill Required Fields!");
        } else {
            sup.createSupplier(ins_supname_txt.getText(), ins_supcontact_txt.getText(), ins_supaddr_txt.getText(), ins_supemail_txt.getText());
            ins_supname_txt.setText("");
            ins_supcontact_txt.setText("");
            ins_supaddr_txt.setText("");
            ins_supemail_txt.setText("");
        }
        sup.closeConnection();
    }//GEN-LAST:event_ins_supadd_btnActionPerformed

    private void upd_supdelete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_supdelete_btnActionPerformed
        // delete supplier
        Supplier sup = new Supplier();
        sup.connectDB();
        if (upd_supid_txt.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill Required Fields!");
        } else {
            int reply = JOptionPane.showConfirmDialog(null,
                    "Are you sure want to delete this supplier?", "Quit", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                sup.deleteSupplier(upd_supid_txt.getText());
                upd_supid_txt.setText("");
                upd_supname_txt.setText("");
                upd_supcontact_txt.setText("");
                upd_supaddr_txt.setText("");
                upd_supemail_txt.setText("");
            }
        }
        sup.closeConnection();
    }//GEN-LAST:event_upd_supdelete_btnActionPerformed

    private void upd_supupdate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_supupdate_btnActionPerformed
        // update supplier
        Supplier sup = new Supplier();
        sup.connectDB();
        if (upd_supid_txt.getText().trim().equals("") || upd_supname_txt.getText().trim().equals("") || upd_supcontact_txt.getText().trim().equals("") || upd_supaddr_txt.getText().trim().equals("") || upd_supemail_txt.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill Required Fields!");
        } else {
            sup.updateSupplier(upd_supid_txt.getText(), upd_supname_txt.getText(), upd_supcontact_txt.getText(), upd_supaddr_txt.getText(), upd_supemail_txt.getText());
            upd_supid_txt.setText("");
            upd_supname_txt.setText("");
            upd_supcontact_txt.setText("");
            upd_supaddr_txt.setText("");
            upd_supemail_txt.setText("");
        }
        sup.closeConnection();
    }//GEN-LAST:event_upd_supupdate_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUpdateSupplierUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUpdateSupplierUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUpdateSupplierUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUpdateSupplierUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUpdateSupplierUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ins_supadd_btn;
    private javax.swing.JTextField ins_supaddr_txt;
    private javax.swing.JTextField ins_supcontact_txt;
    private javax.swing.JTextField ins_supemail_txt;
    private javax.swing.JTextField ins_supname_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField upd_supaddr_txt;
    private javax.swing.JTextField upd_supcontact_txt;
    private javax.swing.JButton upd_supdelete_btn;
    private javax.swing.JTextField upd_supemail_txt;
    private javax.swing.JButton upd_supgo_btn;
    private javax.swing.JTextField upd_supid_txt;
    private javax.swing.JTextField upd_supname_txt;
    private javax.swing.JButton upd_supupdate_btn;
    // End of variables declaration//GEN-END:variables
}
