/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wijesekara.stores.pos;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Samintha
 */
public class AddUpdateSalesmanUI extends javax.swing.JFrame {

    /**
     * Creates new form AddUpdateSalesmanUI
     */
    public AddUpdateSalesmanUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        upd_salupdate_btn = new javax.swing.JButton();
        upd_saldelete_btn = new javax.swing.JButton();
        upd_salid_txt = new javax.swing.JTextField();
        upd_salname_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ins_salname_txt = new javax.swing.JTextField();
        ins_saladd_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        upd_salgo_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add or Update Salesman");
        setResizable(false);

        jLabel1.setText("Update/Delete Salesman");

        jLabel2.setText("Salesman ID :");

        jLabel3.setText("Name :");

        upd_salupdate_btn.setText("Update Details");
        upd_salupdate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_salupdate_btnActionPerformed(evt);
            }
        });

        upd_saldelete_btn.setText("Delete Salesman");
        upd_saldelete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_saldelete_btnActionPerformed(evt);
            }
        });

        jLabel4.setText("Insert a New Salesman");

        jLabel6.setText("Name :");

        ins_saladd_btn.setText("Add Salesman");
        ins_saladd_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_saladd_btnActionPerformed(evt);
            }
        });

        upd_salgo_btn.setText("GO");
        upd_salgo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_salgo_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(upd_salname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ins_salname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(upd_salid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(34, 34, 34)
                                                .addComponent(upd_salgo_btn))))
                                    .addComponent(jLabel4))
                                .addGap(0, 114, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(upd_saldelete_btn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(upd_salupdate_btn))
                                    .addComponent(ins_saladd_btn, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upd_salid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(upd_salgo_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upd_salname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upd_salupdate_btn)
                    .addComponent(upd_saldelete_btn))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ins_salname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ins_saladd_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upd_salgo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_salgo_btnActionPerformed
        // go button
        Salesman sal = new Salesman();
        sal.connectDB();
        List list = sal.getSalesmanDetails(upd_salid_txt.getText());
        if (!list.isEmpty()) {
            upd_salname_txt.setText((String) list.get(1));
        } else {
            JOptionPane.showMessageDialog(null, "Salesman ID not valid!");
        }
        sal.closeConnection();
    }//GEN-LAST:event_upd_salgo_btnActionPerformed

    private void upd_salupdate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_salupdate_btnActionPerformed
        // salesman update
        Salesman sal = new Salesman();
        sal.connectDB();
        if (upd_salid_txt.getText().trim().equals("") || upd_salname_txt.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill Required Fields!");
        } else {
            sal.updateSalesman(upd_salid_txt.getText(), upd_salname_txt.getText());
            upd_salid_txt.setText("");
            upd_salname_txt.setText("");
        }
        sal.closeConnection();
    }//GEN-LAST:event_upd_salupdate_btnActionPerformed

    private void ins_saladd_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_saladd_btnActionPerformed
        // salesman insert
        Salesman sal = new Salesman();
        sal.connectDB();
        if (ins_salname_txt.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill Required Fields!");
        } else {
            sal.createSalesman(ins_salname_txt.getText());
            ins_salname_txt.setText("");
        }
        sal.closeConnection();
    }//GEN-LAST:event_ins_saladd_btnActionPerformed

    private void upd_saldelete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_saldelete_btnActionPerformed
        // salesman delete
        Salesman sal = new Salesman();
        sal.connectDB();
        if (upd_salid_txt.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill Required Fields!");
        } else {
            int reply = JOptionPane.showConfirmDialog(null,
                    "Are you sure want to delete this salesmanr?", "Quit", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                sal.deleteSalesman(upd_salid_txt.getText());
                upd_salid_txt.setText("");
                upd_salname_txt.setText("");
            }
        }
        sal.closeConnection();
    }//GEN-LAST:event_upd_saldelete_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUpdateSalesmanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUpdateSalesmanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUpdateSalesmanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUpdateSalesmanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUpdateSalesmanUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ins_saladd_btn;
    private javax.swing.JTextField ins_salname_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton upd_saldelete_btn;
    private javax.swing.JButton upd_salgo_btn;
    private javax.swing.JTextField upd_salid_txt;
    private javax.swing.JTextField upd_salname_txt;
    private javax.swing.JButton upd_salupdate_btn;
    // End of variables declaration//GEN-END:variables
}
