/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wijesekara.stores.pos;

import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author Samintha
 */
public class AddUpdateCustomerUI extends javax.swing.JFrame {

    /**
     * Creates new form AddUpdateCustomerUI
     */
    public AddUpdateCustomerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        upd_cusid_txt = new javax.swing.JTextField();
        upd_cusgo_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        upd_cusname_txt = new javax.swing.JTextField();
        upd_cuscont_txt = new javax.swing.JTextField();
        upd_cusaddr_txt = new javax.swing.JTextField();
        upd_cusmail_txt = new javax.swing.JTextField();
        upd_cusdel_btn = new javax.swing.JButton();
        upd_cusupdt_btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ins_cusname_txt = new javax.swing.JTextField();
        ins_cuscont_txt = new javax.swing.JTextField();
        ins_cusaddr_txt = new javax.swing.JTextField();
        ins_cusmail_txt = new javax.swing.JTextField();
        ins_cusadd_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add or Update Customer");
        setResizable(false);

        jLabel1.setText("Update/Delete Customer");

        jLabel2.setText("Insert a New Customer");

        jLabel3.setText("Customer ID :");

        upd_cusgo_btn.setText("GO");
        upd_cusgo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_cusgo_btnActionPerformed(evt);
            }
        });

        jLabel4.setText("Name :");

        jLabel5.setText("Contact :");

        jLabel6.setText("Address :");

        jLabel7.setText("Email :");

        upd_cusdel_btn.setText("Delete Customer");
        upd_cusdel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_cusdel_btnActionPerformed(evt);
            }
        });

        upd_cusupdt_btn.setText("Update Details");
        upd_cusupdt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_cusupdt_btnActionPerformed(evt);
            }
        });

        jLabel8.setText("Email :");

        jLabel9.setText("Address :");

        jLabel10.setText("Contact :");

        jLabel11.setText("Name :");

        ins_cusadd_btn.setText("Add Customer");
        ins_cusadd_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_cusadd_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ins_cusname_txt)
                            .addComponent(ins_cuscont_txt)
                            .addComponent(ins_cusaddr_txt)
                            .addComponent(ins_cusmail_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(upd_cusid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(upd_cusgo_btn))
                                            .addComponent(upd_cuscont_txt)
                                            .addComponent(upd_cusaddr_txt)
                                            .addComponent(upd_cusname_txt)
                                            .addComponent(upd_cusmail_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(upd_cusdel_btn)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(upd_cusupdt_btn))
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ins_cusadd_btn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(upd_cusid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upd_cusgo_btn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(upd_cusname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(upd_cuscont_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(upd_cusaddr_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(upd_cusmail_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upd_cusdel_btn)
                    .addComponent(upd_cusupdt_btn))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ins_cusname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ins_cuscont_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ins_cusaddr_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ins_cusmail_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(ins_cusadd_btn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upd_cusgo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_cusgo_btnActionPerformed
        Customer cus = new Customer();
        cus.connectDB();
        List list = cus.getCustomerDetails(upd_cusid_txt.getText());
        if (!list.isEmpty()) {
            upd_cusname_txt.setText((String) list.get(1));
            upd_cuscont_txt.setText((String) list.get(2));
            upd_cusaddr_txt.setText((String) list.get(3));
            upd_cusmail_txt.setText((String) list.get(4));
        } else {
            JOptionPane.showMessageDialog(null, "Customer ID not valid!");
        }
        cus.closeConnection();
    }//GEN-LAST:event_upd_cusgo_btnActionPerformed

    private void upd_cusupdt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_cusupdt_btnActionPerformed
        Customer cus = new Customer();
        cus.connectDB();
        if (upd_cusid_txt.getText().trim().equals("") || upd_cusname_txt.getText().trim().equals("") || upd_cuscont_txt.getText().trim().equals("") || upd_cusaddr_txt.getText().trim().equals("") || upd_cusmail_txt.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill Required Fields!");
        } else {
            cus.updateCustomer(upd_cusid_txt.getText(), upd_cusname_txt.getText(), upd_cuscont_txt.getText(), upd_cusaddr_txt.getText(), upd_cusmail_txt.getText());
            upd_cusid_txt.setText("");
            upd_cusname_txt.setText("");
            upd_cuscont_txt.setText("");
            upd_cusaddr_txt.setText("");
            upd_cusmail_txt.setText("");
        }
        cus.closeConnection();
    }//GEN-LAST:event_upd_cusupdt_btnActionPerformed

    private void ins_cusadd_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_cusadd_btnActionPerformed
        Customer cus = new Customer();
        cus.connectDB();
        if (ins_cusname_txt.getText().trim().equals("") || ins_cuscont_txt.getText().trim().equals("") || ins_cusaddr_txt.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill Required Fields!");
        } else {
            cus.createCustomer(ins_cusname_txt.getText(), ins_cuscont_txt.getText(), ins_cusaddr_txt.getText(), ins_cusmail_txt.getText());
            ins_cusname_txt.setText("");
            ins_cuscont_txt.setText("");
            ins_cusaddr_txt.setText("");
            ins_cusmail_txt.setText("");
        }
        cus.closeConnection();
    }//GEN-LAST:event_ins_cusadd_btnActionPerformed

    private void upd_cusdel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_cusdel_btnActionPerformed
        Customer cus = new Customer();
        cus.connectDB();
        if (upd_cusid_txt.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill Required Fields!");
        } else {
            int reply = JOptionPane.showConfirmDialog(null,
                    "Are you sure want to delete this customer?", "Quit", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                cus.deleteCustomer(upd_cusid_txt.getText());
                upd_cusid_txt.setText("");
                upd_cusname_txt.setText("");
                upd_cuscont_txt.setText("");
                upd_cusaddr_txt.setText("");
                upd_cusmail_txt.setText("");
            }
        }
        cus.closeConnection();
    }//GEN-LAST:event_upd_cusdel_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUpdateCustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUpdateCustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUpdateCustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUpdateCustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUpdateCustomerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ins_cusadd_btn;
    private javax.swing.JTextField ins_cusaddr_txt;
    private javax.swing.JTextField ins_cuscont_txt;
    private javax.swing.JTextField ins_cusmail_txt;
    private javax.swing.JTextField ins_cusname_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField upd_cusaddr_txt;
    private javax.swing.JTextField upd_cuscont_txt;
    private javax.swing.JButton upd_cusdel_btn;
    private javax.swing.JButton upd_cusgo_btn;
    private javax.swing.JTextField upd_cusid_txt;
    private javax.swing.JTextField upd_cusmail_txt;
    private javax.swing.JTextField upd_cusname_txt;
    private javax.swing.JButton upd_cusupdt_btn;
    // End of variables declaration//GEN-END:variables
}
