/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wijesekara.stores.pos;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Samintha
 */
public class AdminAuthenticateUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminAuthenticateUI
     */
    public AdminAuthenticateUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        admin_auth_pass_btn = new javax.swing.JButton();
        admin_auth_pass_txt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Authentication");
        setResizable(false);

        jLabel1.setText("Enter Administrator Password to Continue");

        admin_auth_pass_btn.setText("OK");
        admin_auth_pass_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_auth_pass_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(admin_auth_pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(admin_auth_pass_btn)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(admin_auth_pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(admin_auth_pass_btn)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admin_auth_pass_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_auth_pass_btnActionPerformed
        if (admin_auth_pass_txt.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill the Required Fields!");
        } else {
            MD5Converter md5cnvtr = new MD5Converter();
            String adminAuthenticationPassword = md5cnvtr.md5(admin_auth_pass_txt.getText());
            
            //connect db to see if password is correct
            MySqlDBConnect db = new MySqlDBConnect();
            db.connectDB();
            
            if (db.adminAuthenticationToContinue(adminAuthenticationPassword)) {
                if (MainClassUI.whereToRedirect.equals("ProductUI")) {
                    //load suppliers
                    Supplier db_sup = new Supplier();
                    db_sup.connectDB();

                    AddUpdateProductUI aup = new AddUpdateProductUI();
                    aup.pack();
                    aup.setLocationRelativeTo(null);

                    //load supplier name to combo box
                    List<String> ls = db_sup.LoadSuppliers();
                    aup.ins_supname_cmb.setModel(new DefaultComboBoxModel(ls.toArray()));
                    aup.upd_supname_cmb.setModel(new DefaultComboBoxModel(ls.toArray()));

                    aup.setVisible(true);

                } else if (MainClassUI.whereToRedirect.equals("SupplierUI")) {
                    AddUpdateSupplierUI aus = new AddUpdateSupplierUI();
                    aus.pack();
                    aus.setLocationRelativeTo(null);
                    aus.setVisible(true);
                } else if (MainClassUI.whereToRedirect.equals("SalesmanUI")) {
                    AddUpdateSalesmanUI aus = new AddUpdateSalesmanUI();
                    aus.pack();
                    aus.setLocationRelativeTo(null);
                    aus.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Administrator Password is Incorrect!");
            }

            db.closeConnection();

            this.dispose();
        }
    }//GEN-LAST:event_admin_auth_pass_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAuthenticateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAuthenticateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAuthenticateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAuthenticateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAuthenticateUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_auth_pass_btn;
    private javax.swing.JPasswordField admin_auth_pass_txt;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
