/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wijesekara.stores.pos;

import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samintha
 */
public class MainClassUI extends javax.swing.JFrame {

    int productTableID = 0;

    private class MainClassUIKeyManager implements KeyEventDispatcher {

        //this class controls all the key events
        //key press events goes here
        @Override
        public boolean dispatchKeyEvent(KeyEvent e) {
            if (e.getID() == KeyEvent.KEY_PRESSED) {
                //F1
                if (e.getKeyCode() == KeyEvent.VK_F1) {
                    // executre clearWholeWindow() on F1 key press
                    int reply = JOptionPane.showConfirmDialog(null,
                            "Are You Sure You Want to Clear All and Go for New Transaction?", "New", JOptionPane.YES_NO_OPTION);
                    if (reply == JOptionPane.YES_OPTION) {
                        clearWholeWindow();
                    }
                }

                //F2
                if (e.getKeyCode() == KeyEvent.VK_F2) {
                    // save current transaction to database
                    int reply = JOptionPane.showConfirmDialog(null,
                            "Press Yes to Proceed with Save?", "Save", JOptionPane.YES_NO_OPTION);
                    if (reply == JOptionPane.YES_OPTION) {
                        if (productTable.getRowCount() > 0) {
                            save_transaction();
                        } else {
                            JOptionPane.showMessageDialog(null, "Please insert items to the order list to proceed.");
                        }
                    }
                }
            }
            return false;
        }
    }

    /**
     * Creates new form MainClassUI
     */
    public MainClassUI() {
        initComponents();
        autoStart();

        //key events invokes
        KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        manager.addKeyEventDispatcher(new MainClassUIKeyManager());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        newOdr_btn = new javax.swing.JButton();
        saveOdr_btn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        editRowOrder_btn = new javax.swing.JButton();
        removeRowOrder_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        date_txt = new javax.swing.JTextField();
        time_txt = new javax.swing.JTextField();
        salesman_combo = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        barcode_txt = new javax.swing.JTextField();
        quantity_txt = new javax.swing.JTextField();
        discount_txt = new javax.swing.JTextField();
        barcodeadd_btn = new javax.swing.JButton();
        barcodecancel_btn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        total_lbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        total_txt = new javax.swing.JTextField();
        paid_txt = new javax.swing.JTextField();
        due_txt = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Wijesekara POS");
        setLocation(new java.awt.Point(0, 0));
        setName("mainFrame"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 650));

        newOdr_btn.setLabel("New (F1)");
        newOdr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOdr_btnActionPerformed(evt);
            }
        });

        saveOdr_btn.setLabel("Save (F2)");
        saveOdr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveOdr_btnActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        jButton6.setText("jButton6");

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1220, 477));

        productTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Barcode Entry", "Item Number", "Description", "Discount %", "Qty", "Each", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productTable);

        editRowOrder_btn.setText("Edit");
        editRowOrder_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRowOrder_btnActionPerformed(evt);
            }
        });

        removeRowOrder_btn.setText("Remove");
        removeRowOrder_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRowOrder_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeRowOrder_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(editRowOrder_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(editRowOrder_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(removeRowOrder_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(142, 142, 142))
        );

        jTabbedPane1.addTab("Order", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1119, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Transactions", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1119, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Suppliers", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1119, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Customer", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));

        jLabel1.setText("Date :");

        jLabel2.setText("Time :");

        jLabel3.setText("Salesman :");

        date_txt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        date_txt.setEnabled(false);

        time_txt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        time_txt.setEnabled(false);

        salesman_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(date_txt)
                    .addComponent(time_txt)
                    .addComponent(salesman_combo, 0, 110, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(date_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(salesman_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        date_txt.getAccessibleContext().setAccessibleName("date_text");
        time_txt.getAccessibleContext().setAccessibleName("time_text");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Entry"));

        jLabel4.setText("Barcode Entry :");

        jLabel5.setText("Quantity :");

        jLabel6.setText("Discount for Each :");

        quantity_txt.setToolTipText("");
        quantity_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantity_txtKeyTyped(evt);
            }
        });

        discount_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                discount_txtKeyTyped(evt);
            }
        });

        barcodeadd_btn.setText("Add");
        barcodeadd_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeadd_btnActionPerformed(evt);
            }
        });

        barcodecancel_btn.setText("Cancel");
        barcodecancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodecancel_btnActionPerformed(evt);
            }
        });

        jLabel12.setText("%");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(barcode_txt)
                            .addComponent(quantity_txt)
                            .addComponent(discount_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(barcodeadd_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(barcodecancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(barcode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(quantity_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(discount_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barcodeadd_btn)
                    .addComponent(barcodecancel_btn))
                .addContainerGap())
        );

        barcode_txt.getAccessibleContext().setAccessibleName("sku_text");
        quantity_txt.getAccessibleContext().setAccessibleName("qty_text");
        discount_txt.getAccessibleContext().setAccessibleName("disc_text");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));

        jLabel7.setText("Total :");

        jLabel8.setText("Paid :");

        jLabel9.setText("Due :");

        total_lbl.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        total_lbl.setText("0.0");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel11.setText("LKR");

        total_txt.setText("0.0");
        total_txt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        total_txt.setEnabled(false);

        paid_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paid_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paid_txtKeyTyped(evt);
            }
        });

        due_txt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        due_txt.setEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(total_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(paid_txt)
                    .addComponent(due_txt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(total_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(110, 110, 110))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(total_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(paid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(due_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_lbl)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        total_lbl.getAccessibleContext().setAccessibleName("total_label");
        total_txt.getAccessibleContext().setAccessibleName("total_text");
        paid_txt.getAccessibleContext().setAccessibleName("paid_text");
        due_txt.getAccessibleContext().setAccessibleName("due_text");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(newOdr_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(saveOdr_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveOdr_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newOdr_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Order");

        jMenu1.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Add");

        jMenuItem3.setText("Add Item");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Add Salesman");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Help");

        jMenuItem5.setText("About");
        jMenu6.add(jMenuItem5);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1144, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, 629, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void autoStart() {
        //set table to only select one record at a time
        productTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        //right align the total label
        total_lbl.setHorizontalAlignment(SwingConstants.RIGHT);

        //set text on date_txt and time_txt
        t.start();

        //load salesmans
        MySqlDBConnect db = new MySqlDBConnect();
        db.connectDB();

        List<String> ls = db.LoadSalesmans();
        salesman_combo.setModel(new DefaultComboBoxModel(ls.toArray()));

        db.closeConnection();
    }

    DateFormat timeF = new SimpleDateFormat("HH:mm:ss");
    DateFormat dateF = new SimpleDateFormat("dd/MM/yyyy");
    Timer t = new Timer(500, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            Date date = new Date();
            time_txt.setText(timeF.format(date));
            date_txt.setText(dateF.format(date));
            repaint();
        }
    });

    public static void countTotalAndDisplay() {
        float total = 0;
        for (int i = 0; i < productTable.getRowCount(); i++) {
            total = total + (Float) productTable.getModel().getValueAt(i, 7);
        }
        total_lbl.setText(String.format("%.02f", total) + "");
        total_txt.setText(String.format("%.02f", total) + "");
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int reply = JOptionPane.showConfirmDialog(null,
                "Are You Really Want to Quit ?", "Quit", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int reply = JOptionPane.showConfirmDialog(null,
                "Are You Really Want to Quit ?", "Quit", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void barcodeadd_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeadd_btnActionPerformed
        // Enter bacode and press Add button    
        MySqlDBConnect db = new MySqlDBConnect();
        db.connectDB();

        //if user didn't enter quantity it will automatically be one
        //if user didn't enter discount it will automatically be discount value
        //in the database.
        int auto_quantity = 1, auto_discount = db.productDiscount(barcode_txt.getText());

        if (!discount_txt.getText().equals("") && Integer.parseInt(discount_txt.getText()) <= 50) {
            auto_discount = Integer.parseInt(discount_txt.getText());
        } else if (!discount_txt.getText().equals("") && Integer.parseInt(discount_txt.getText()) > 50) {
            JOptionPane.showMessageDialog(null, "Set the discount below 50%. Default value will be set for now!");
        }

        if (quantity_txt.getText().equals("")) {
            auto_quantity = 1;
        } else {
            auto_quantity = Integer.parseInt(quantity_txt.getText());
        }

        List list = db.BarcodeEntryAdd(barcode_txt.getText());
        if (!list.isEmpty()) //list.forEach(System.out::println);
        {
            //check if items are available and then add to the list
            if (db.productQuantity(barcode_txt.getText()) > 0 && db.productQuantity(barcode_txt.getText()) >= auto_quantity) {
                boolean previousRecordFound = false;
                //insert record for the first time
                if (productTable.getRowCount() == 0) {
                    DefaultTableModel model = (DefaultTableModel) productTable.getModel();
                    model.addRow(new Object[]{" " + (++productTableID), list.get(0), list.get(1), list.get(2), auto_discount, auto_quantity, (Float) list.get(3), (((Float) list.get(3) * auto_quantity) - (((Float) list.get(3) * auto_quantity * auto_discount) / 100))});
                } else if (productTable.getRowCount() > 0) {
                    //if the same barcode entered before, this will look through the table and edit previously endtered record.
                    for (int i = 0; i < productTable.getRowCount(); i++) {
                        if (productTable.getModel().getValueAt(i, 1).equals(barcode_txt.getText())) {
                            // Edit row if the entry already exists
                            EditOrderWindow edito = new EditOrderWindow(barcode_txt.getText(), Integer.parseInt(productTable.getModel().getValueAt(i, 5).toString()), Integer.parseInt(productTable.getModel().getValueAt(i, 4).toString()), Float.parseFloat(productTable.getModel().getValueAt(i, 6).toString()));
                            edito.pack();
                            edito.setLocationRelativeTo(null);
                            edito.setVisible(true);
                            previousRecordFound = true;
                        }
                    }
                    if (!previousRecordFound) {
                        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
                        model.addRow(new Object[]{" " + (++productTableID), list.get(0), list.get(1), list.get(2), auto_discount, auto_quantity, (Float) list.get(3), (((Float) list.get(3) * auto_quantity) - (((Float) list.get(3) * auto_quantity * auto_discount) / 100))});
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Products are not available for entered quantity!");
            }

            //System.out.println("barcode " + list.get(0) + " itemnum " + list.get(1) + " decription " + list.get(2) + " price " + (Float) list.get(3) + " discount " + (Integer) list.get(4) + " available_items " + (Integer) list.get(5));
        } else {
            JOptionPane.showMessageDialog(null, "Barcode entry error!");
        }

        //show total on text fields
        countTotalAndDisplay();

        //clear text fields
        barcode_txt.setText("");
        quantity_txt.setText("");
        discount_txt.setText("");
        paid_txt.setText("");
        due_txt.setText("");

        db.closeConnection();
    }//GEN-LAST:event_barcodeadd_btnActionPerformed

    private void editRowOrder_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRowOrder_btnActionPerformed
        // Edit row of product orders
        if (productTable.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Please select a record to edit.");
        } else {
            EditOrderWindow edito = new EditOrderWindow(productTable.getValueAt(productTable.getSelectedRow(), 1).toString(), Integer.parseInt(productTable.getModel().getValueAt(productTable.getSelectedRow(), 5).toString()), Integer.parseInt(productTable.getModel().getValueAt(productTable.getSelectedRow(), 4).toString()), Float.parseFloat(productTable.getModel().getValueAt(productTable.getSelectedRow(), 6).toString()));
            edito.pack();
            edito.setLocationRelativeTo(null);
            edito.setVisible(true);
        }
    }//GEN-LAST:event_editRowOrder_btnActionPerformed

    private void quantity_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantity_txtKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_quantity_txtKeyTyped

    private void discount_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discount_txtKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_discount_txtKeyTyped

    private void removeRowOrder_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRowOrder_btnActionPerformed
        // remove selected row
        if (productTable.getSelectedRow() != -1) {
            // remove selected row from the model
            DefaultTableModel model = (DefaultTableModel) productTable.getModel();
            model.removeRow(productTable.getSelectedRow());
            paid_txt.setText("");
            due_txt.setText("");
            countTotalAndDisplay();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a record to delete.");
        }
    }//GEN-LAST:event_removeRowOrder_btnActionPerformed

    private void paid_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paid_txtKeyTyped
        if (paid_txt.getText().contains(".")) {
            char c = evt.getKeyChar();
            if (!((c >= '0') && (c <= '9')
                    || (c == KeyEvent.VK_BACK_SPACE)
                    || (c == KeyEvent.VK_DELETE))) {
                getToolkit().beep();
                evt.consume();
            }
        } else if (paid_txt.getText().trim().equals("")) {
            char c = evt.getKeyChar();
            if (!((c >= '0') && (c <= '9')
                    || (c == KeyEvent.VK_BACK_SPACE)
                    || (c == KeyEvent.VK_DELETE))) {
                getToolkit().beep();
                evt.consume();
            }
        } else {
            char c = evt.getKeyChar();
            if (!((c >= '0') && (c <= '9')
                    || (c == KeyEvent.VK_BACK_SPACE)
                    || (c == KeyEvent.VK_DELETE)
                    || (c == '.'))) {
                getToolkit().beep();
                evt.consume();
            }
        }
    }//GEN-LAST:event_paid_txtKeyTyped

    private void paid_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paid_txtKeyReleased
        if ((!paid_txt.getText().trim().equals("") && (Double.parseDouble(total_txt.getText()) <= Double.parseDouble(paid_txt.getText())))) {
            double due_amount = Double.parseDouble(paid_txt.getText()) - Double.parseDouble(total_txt.getText());
            due_txt.setText("" + String.format("%.02f", due_amount));
        } else {
            due_txt.setText("");
        }
    }//GEN-LAST:event_paid_txtKeyReleased

    private void saveOdr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveOdr_btnActionPerformed
        // save current transaction to database
        int reply = JOptionPane.showConfirmDialog(null,
                "Press Yes to Proceed with Save?", "Save", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            if (productTable.getRowCount() > 0) {
                save_transaction();
            } else {
                JOptionPane.showMessageDialog(null, "Please insert items to the order list to proceed.");
            }
        }
    }//GEN-LAST:event_saveOdr_btnActionPerformed

    private void barcodecancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodecancel_btnActionPerformed
        barcode_txt.setText("");
        quantity_txt.setText("");
        discount_txt.setText("");
    }//GEN-LAST:event_barcodecancel_btnActionPerformed

    private void newOdr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOdr_btnActionPerformed
        int reply = JOptionPane.showConfirmDialog(null,
                "Are You Sure You Want to Clear All and Go for New Transaction?", "New", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            clearWholeWindow();
        }
    }//GEN-LAST:event_newOdr_btnActionPerformed

    public void save_transaction() {
        try {
            MySqlDBConnect db = new MySqlDBConnect();
            db.connectDB();

            int orderID = db.getNextOrderId();
            int smid = db.getSalesmanID((String) salesman_combo.getSelectedItem());

            for (int i = 0; i < productTable.getRowCount(); i++) {

                int productID = db.getProductID((String) productTable.getModel().getValueAt(i, 1));
                int discount = (int) productTable.getModel().getValueAt(i, 4);
                int quantity = (int) productTable.getModel().getValueAt(i, 5);
                float price = (float) productTable.getModel().getValueAt(i, 6);
                float total = (float) productTable.getModel().getValueAt(i, 7);

                db.substractProductQuantity((String) productTable.getModel().getValueAt(i, 1), (int) productTable.getModel().getValueAt(i, 5));
                db.insertTransaction(orderID, productID, price, discount, quantity, total, smid);
            }

            db.closeConnection();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Fatal Error!");
        }
    }

    public static void editRecord(String barcode, int quantity, int discount, float price) {
        //this method invoke from the EditOrderWindow class
        MySqlDBConnect db = new MySqlDBConnect();
        db.connectDB();

        //check if entered quantity available in the database
        if (db.productQuantity(barcode) >= quantity && discount <= 50) {
            for (int i = 0; i < productTable.getRowCount(); i++) {
                if (productTable.getModel().getValueAt(i, 1).equals(barcode)) {
                    // Search for the row and edit it
                    DefaultTableModel model = (DefaultTableModel) productTable.getModel();
                    model.setValueAt(quantity, i, 5);
                    model.setValueAt(discount, i, 4);
                    model.setValueAt(price, i, 6);
                    model.setValueAt(((price * quantity) - ((price * quantity * discount) / 100)), i, 7);
                }
            }
        } else if (discount > 50) {
            JOptionPane.showMessageDialog(null, "Set discount lower than 50%!");
        } else {
            JOptionPane.showMessageDialog(null, "Products are not available for entered quantity!");
        }
        paid_txt.setText("");
        due_txt.setText("");
        countTotalAndDisplay();
        db.closeConnection();
    }

    public void clearWholeWindow() {
        DefaultTableModel tMOdel = (DefaultTableModel) productTable.getModel();
        tMOdel.setRowCount(0);

        countTotalAndDisplay();

        barcode_txt.setText("");
        quantity_txt.setText("");
        discount_txt.setText("");
        paid_txt.setText("");
        due_txt.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainClassUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField barcode_txt;
    private javax.swing.JButton barcodeadd_btn;
    private javax.swing.JButton barcodecancel_btn;
    private javax.swing.JTextField date_txt;
    private javax.swing.JTextField discount_txt;
    private static javax.swing.JTextField due_txt;
    private javax.swing.JButton editRowOrder_btn;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton newOdr_btn;
    private static javax.swing.JTextField paid_txt;
    private static javax.swing.JTable productTable;
    private javax.swing.JTextField quantity_txt;
    private javax.swing.JButton removeRowOrder_btn;
    private javax.swing.JComboBox<String> salesman_combo;
    private javax.swing.JButton saveOdr_btn;
    private javax.swing.JTextField time_txt;
    private static javax.swing.JLabel total_lbl;
    private static javax.swing.JTextField total_txt;
    // End of variables declaration//GEN-END:variables

}
